# docker/docker-compose.yml
# version: "3.8"

networks:
  navex-crm-symfony:

services:
  #php-service
  php-service:
    container_name: php-fpm
    build:
      args:
        VERSION: ${PHP_VERSION}
      context: docker/php-fpm
    environment:
      - APP_ENV=${APP_ENV}
      - APP_SECRET=${APP_SECRET}
    volumes:
      - ${APP_FOLDER}:/var/www
    networks:
      - navex-crm-symfony

  #nginx-service
  nginx-service:
    container_name: nginx-container
    build:
      args:
        VERSION: ${NGNX_VERSION}
      context: docker/nginx
    volumes:
      - ${APP_FOLDER}:/var/www
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/log:/var/log/nginx
    expose:
      - "8000"
    depends_on:
      - php-service
      - mysql-service
      - rabbitmq-service
      - mailer-service
    ports:
      - "8000:80"
    networks:
      - navex-crm-symfony

  #mysql-service
  mysql-service:
    build:
      args:
        VERSION: ${MYSQL_VERSION}
      context: docker/database
    volumes:
      - ./docker/database/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./docker/database/data:/var/lib/mysql
    #command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci', '--default-authentication-plugin=mysql_native_password']
    restart: always
    ports:
      - '3306:3306'
    environment:
      MYSQL_DATABASE: ${DATABASE_NAME}
      # MYSQL_USER: ${DATABASE_USER}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
    networks:
      - navex-crm-symfony

  #phpmyadmin-service
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin-container
    restart: always
    ports:
      - '8081:80'
    environment:
      PMA_HOST: mysql-service
    depends_on:
      - mysql-service

    networks:
      - navex-crm-symfony

  #rabbitmq-service
  rabbitmq-service:
    image: rabbitmq:3.9-management
    ports:
      - '5672:5672'
      - '15672:15672'
    networks:
      - navex-crm-symfony

  #mailer-service
  mailer-service:
    image: axllent/mailpit
    container_name: mailer
    ports:
      - ${CUSTOM_UI_PORT}:8025
      - ${CUSTOM_SMTP_PORT}:1025
    environment:
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1
    networks:
      - navex-crm-symfony